openapi: 3.0.2
servers: []
info:
  version: "draft.3.1"
  title: GA4GH Beacon Variant Annotation Default Schema
  description: >-
    Schema for variant annotations to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    Beacon Project
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    GenomicFeature:
      description: |
        Genomic feature(s) affected by the variant.
      type: object
      properties:
        class:
          allOf:
            - description: |
                Class of feature affected by the variant. Value from ENSGLOSS 
                Biotype (ENSGLOSSARY:0000025) ontology, e.g. protein coding gene, 
                non-coding RNA, long non-coding RNA.
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'ENSGLOSSARY:0000026'
                label: 'protein coding'
        featureId:
          description: |
            ID/accession/name of genomic region affected by the variant, 
            matching class in `class`.
          type: string
          example:
            - 'TP53'
            - 'GeneID:43740578'
    VariantAnnotation:
      description: TBD # TBD
      type: object
      required:
        - variantId
      properties:
        variantId:
          description: |
            Reference to Variant ID.
          type: string
        variantAlternativeIds:
          description: |
            List of cross-referencing ID(s) (CURIE(s)) for the variant in the 
            original databases or variant-level (aggregated) databases for 
            previously described variants (e.g. clinVarId, ClinGen, COSMIC), 
            e.g. VCV000055583.1, CA003602.
          type: array
          items:
            type: string
          example: 
            - 'rs80356868'
            - 'CA003602'
            - 'VCV000055583.1'
        genomicHGVSId:
          description: |
            HGVSId descriptor at genomic level (recommended, referred to genome 
            assembly defined in Variant Identification).
          type: string
          example: 'NC_000011.9:g.134086816T>C'
        transcriptHGVSIds:
          description: |
            List of HGVSId descriptor(s) at transcript level.
          type: array
          items:
            type: string
          example: 
            - 'NC 000023.10(NM004006.2):c.357+1G'
        proteinHGVSIds:
          description: |
            List of HGVSId descriptor(s) at protein level (for protein-altering 
            variants), e.g. NP 009225.1:p.Glu1817Ter or LRG 199p1:p.Val25Gly 
            (preferred).
          type: array
          items:
            type: string
          example: 
            - 'NP_009225.1:p.Glu1817Ter'
            - 'LRG 199p1:p.Val25Gly'
        genomicRegions:
          description: |
            List of classification(s) of the variant according to the genomic 
            region affected (all that apply, relative to each feature affected). 
            Value from Ensembl Glossary (ENSGLOSS).
          type: array
          items:
            allOf:
              - $ref: 'common.yaml#/components/schemas/OntologyTerm'
              - example: 
                  id: 'ENSGLOSSARY:0000159'
                  label: '3UTR'
        genomicFeatures:
          description: |
            List of genomic feature(s) affected by the variant.
          type: array
          items:
            $ref: '#/components/schemas/GenomicFeature'
        molecularEffects:
          description: |
            List of predicted effect at nucleotide level for protein affecting 
            variants. Value from Sequence ontology (SO) coding sequence variant 
            (SO:0001580) ontology, e.g. synonymous variant (SO:0001819), 
            nonsynonymous variant (SO:0001992), and classifications therein, 
            such as stop gained (SO:0001587), missense variant (SO:0001583), 
            inframe indel (SO:0001820).
          type: array
          items:
            allOf:
              - $ref: 'common.yaml#/components/schemas/OntologyTerm'
              - example:
                  id: 'SO:0001587'
                  label: 'stop gained'
        aminoacidChange:
          description: |
            Lisf of changes at aminoacid level for protein affecting missense 
            variants. 
          type: array
          items:
            type: string
          example:
            - 'V304*'
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue