openapi: 3.0.2
servers: []
info:
  version: "draft.3.1"
  title: GA4GH Beacon Run Default Schema
  description: >-
    Schema for runs to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    Beacon Project
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    Run:
      description: |
        TBD
      type: object
      required:
        - runId
        - biosampleId
      properties:
        runId:
          description: |
            Run reference ID (external accession or internal ID).
          type: string
          example: 'SRR10903401'
        biosampleId:
          description: |
            Reference to Biosample ID.
          type: string
          example: 'S0001'
        runDate:
          description: |
            Date at which run was performed in ISO8601 date format.
          type: string
          format: date
          example: '2019-12-28'
        librarySource:
          description: |
            Ontology value for sequencing library source e.g "Metagenomic", 
            "Viral RNA".
          type: string
          example:
            - 'Metagenomic'
            - 'Viral RNA'
        librarySelection:
          description: |
            Selection method for sequencing library preparation, e.g "RANDOM", 
            "RT-PCR".
          type: string
          example:
            - 'RANDOM'
            - 'RT-PCR'
        libraryStrategy:
          description: |
            Sequencing library strategy, e.g. "WGS".
          type: string
          example:
            - 'WGS'
        libraryLayout:
          description: |
            Ontology value for sequencing library layout e.g "PAIRED", "SINGLE".
          type: string
          enum:
            - 'PAIRED'
            - 'SINGLE'
          example: 'SINGLE'
        platform:
          description: |
            Ontology value for sequencing technology, e.g. "Illumina", "Oxford 
            Nanopore Technologies".
          type: string
          example:
            - 'Illumina'
            - 'Oxford Nanopore Technologies'
        platformModel:
          description: |
            Ontology value for sequencing platform model e.g "Illumina MiSeq", 
            "GridION".
          type: string
          example:
            - 'Illumina'
            - 'Oxford Nanopore Technologies'
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue3