openapi: 3.0.2
servers: []
info:
  version: "draft.3.1"
  title: GA4GH Beacon Interactor Default Schema
  description: |
    Schema for interactor to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    Beacon project
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    Interactor:
      allOf:
        - description: |
            TBD
        - type: object
          required:
            - interactorId
            - individualId
          properties:
            interactorId:
              description: |
                Interactor organism/ agent reference ID (external accession or 
                internal ID).
              type: string
            relationType:
              allOf:
                - $ref: 'common.yaml#/components/schemas/OntologyTerm'
                - description: |
                   Value  from Infectious disease Ontology(IDO), e.g. host 
                   (IDO:0000531), commensal (IDO:0000525), infectious agent 
                   (IDO:0000596).
                - example: 
                    id: 'IDO:0000531'
                    label: 'host'
        - $ref: 'default_individual_schema.yaml#/components/schemas/Individual'
